In [6]:
import numpy as np
import pandas as pd

In [8]:
df=pd.read_csv('C:\\Users\Windows\_ANCONDA WORKSHOP\_VAMSHI SIR\datasets\PlayTennis.csv')

In [12]:
df12=df

In [18]:
df.drop(['Humidity','Wind'],axis=1,inplace=True)

In [22]:
df.rename(columns={'Outlook':'weather','Temperature':'temp','Play Tennis':'play'},inplace=True)

In [25]:
df.head(1)

weather temp play
0   Sunny  Hot   No

In [28]:
# encoding for weather column
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
weather_encoded=le.fit_transform(df.weather)
print(weather_encoded)

[2 2 0 1 1 1 0 2 2 1 2 0 0 1]


In [30]:
# encoding for temp column
temp_encoded=le.fit_transform(df.temp)
print(temp_encoded)

[1 1 1 2 0 0 0 2 0 2 2 2 1 2]


In [31]:
# encoding for play column
play_encoded=le.fit_transform(df.play)
print(play_encoded)

[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [35]:
features=list(zip(weather_encoded,temp_encoded))
features=pd.DataFrame(features)

Naive Bayes

In [36]:
from sklearn.naive_bayes import GaussianNB

In [38]:
model=GaussianNB()
model.fit(features,play)

GaussianNB(priors=None, var_smoothing=1e-09)

In [39]:
model.predict([[0,2]])

array(['Yes'], dtype='<U3')