# BASICS

In [13]:
x=5
y='10'

In [15]:
z=x+int(y)

In [16]:
z

15

In [143]:
x='i have a good name by systematic approaches made by a company my parents took advice for my name from'
len(x)

101

In [144]:
new = x.split()

In [146]:
print(new)
len(new)

['i', 'have', 'a', 'good', 'name', 'by', 'systematic', 'approaches', 'made', 'by', 'a', 'company', 'my', 'parents', 'took', 'advice', 'for', 'my', 'name', 'from']


20

In [54]:
splitfuntion=['i', 'have', 'a', 'good', 'name', 'by', 'systematic', 'approaches', 'made', 'by', 'a', 'company', 'my', 'parents', 'took', 'advice', 'for', 'my', 'name', 'from']

In [65]:
"  ".join(splitfuntion)

'i  have  a  good  name  by  systematic  approaches  made  by  a  company  my  parents  took  advice  for  my  name  from'

In [5]:
variable_a="an_apple"

In [6]:
j=1
for i in variable_a:
    print("index {letter} in string is {i}".format(letter=j,i=i))
    j+=1

index 1 in string is a
index 2 in string is n
index 3 in string is _
index 4 in string is a
index 5 in string is p
index 6 in string is p
index 7 in string is l
index 8 in string is e


# LAMBDA - FILTER - MAP

In [87]:
A=lambda x: x**x

In [88]:
A(5)

3125

In [140]:
b=lambda x,y,z:x*y*z

In [141]:
b(5,2,4)

40

In [142]:
b=(lambda x,y,z:x*y*z)(1,2,3)

6

In [ ]:
#LAMBDA WITH filter(function, sequence)
def even_f(n):
    if n%2==0:
        return True
    else:
        return False
list_range=range(1,100)
list2=list(filter(even_f,list_range))
print(list2)

In [105]:
list3 = list(filter(lambda x:x%2==0,range(100)))
print(list3)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


In [109]:
#LAMBDA WITH map(function, sequence)
listof=range(101)
listp=list(map(lambda i:i**2,listof))
print(listp)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801, 10000]


# REDUCE

In [121]:
def factorial(n):
    prod=1
    for i in range(1,n):
        prod=prod*i
    print(prod)

In [127]:
factorial(10)

362880


In [128]:
help


Type help() for interactive help, or help(object) for help about object.

In [132]:
from functools import reduce 
prod=reduce(lambda x,y:x*y,range(1,5))
print(prod)

24


In [133]:
value= lambda x,y: x if x>y else y

In [135]:
reduce(value,[23,4,56,711,34,89])

711

# Date-24-09-2019

In [4]:
x="I am a data Scientist"
y= x.split()
type(y)
type(str(y))

str

In [12]:
for i in range(23):
        k=i**2
        if k>5 and k<500:
            print(k)

9
16
25
36
49
64
81
100
121
144
169
196
225
256
289
324
361
400
441
484


In [12]:
square(11)

9
16
25
36
49


In [5]:
import os
os.getcwd()

'C:\\Users\\Windows'

In [18]:
os.chdir("D:\\DS")

In [26]:
musicfile=open("‪\New folder\New Text Document.txt")

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 10-11: malformed \N character escape (<ipython-input-26-3b7102741a69>, line 1)

In [ ]:
os.getcwd()

In [150]:
a=['i', 'have', 'a', 'good', 'name', 'by', 'systematic', 'approaches', 'made', 'by', 'a', 'company', 'my', 'parents', 'took', 'advice', 'for', 'my', 'name', 'from']
length=[]
for i in a:
    length.append(len(i))
print(length)    

[1, 4, 1, 4, 4, 2, 10, 10, 4, 2, 1, 7, 2, 7, 4, 6, 3, 2, 4, 4]


# LIST COMPREHENSIONS

In [156]:
listmain=['Anne', 'Amy', 'Bob', 'David', 'Carrie', 'Barbara', 'Zach']

In [180]:
list2=[i[-2] for i in listmain]
print(list2)

['n', 'm', 'o', 'i', 'i', 'r', 'c']


In [182]:
list3 =[len(x) for x in listmain ]
print(list3)

[4, 3, 3, 5, 6, 7, 4]


In [184]:
list4=[x[::-1] for x in listmain]
print(list4)

['ennA', 'ymA', 'boB', 'divaD', 'eirraC', 'arabraB', 'hcaZ']


In [186]:
list5=[x[-1] for x in list4]
print(list5)

['A', 'A', 'B', 'D', 'C', 'B', 'Z']


In [191]:
list6=[(x,x[0],len(x)) for x in listmain]
print(list6)

[('Anne', 'A', 4), ('Amy', 'A', 3), ('Bob', 'B', 3), ('David', 'D', 5), ('Carrie', 'C', 6), ('Barbara', 'B', 7), ('Zach', 'Z', 4)]


In [196]:
list7=[1,2,3]
list8=['one','two','three']
list9=['1ne','2wo','3ree']
list7_8_9=[[x,y,z] for x in list7 for y in list8 for z in list9]
print(list7_8_9)

[[1, 'one', '1ne'], [1, 'one', '2wo'], [1, 'one', '3ree'], [1, 'two', '1ne'], [1, 'two', '2wo'], [1, 'two', '3ree'], [1, 'three', '1ne'], [1, 'three', '2wo'], [1, 'three', '3ree'], [2, 'one', '1ne'], [2, 'one', '2wo'], [2, 'one', '3ree'], [2, 'two', '1ne'], [2, 'two', '2wo'], [2, 'two', '3ree'], [2, 'three', '1ne'], [2, 'three', '2wo'], [2, 'three', '3ree'], [3, 'one', '1ne'], [3, 'one', '2wo'], [3, 'one', '3ree'], [3, 'two', '1ne'], [3, 'two', '2wo'], [3, 'two', '3ree'], [3, 'three', '1ne'], [3, 'three', '2wo'], [3, 'three', '3ree']]


In [201]:
list11=[x**2 for x in range(11) if x**2>4 and x**2<100]
print(list11)

[9, 16, 25, 36, 49, 64, 81]


In [204]:
square=[x**2 for x in range(11)]
list13=[x for x in square if x>4 and x<50]
list13

[9, 16, 25, 36, 49]

In [206]:
list14=[x for x in [x**2 for x in range(11)] if x>4 and x<50]
list14


[9, 16, 25, 36, 49]

In [208]:
list15=[x for x in listmain if x.startswith("B")]
list15

['Bob', 'Barbara']


# Date-25-09-2019

In [7]:
import numpy as np

In [13]:
array= np.array([1,2,3,4,5,6])

In [3]:
array

array([1, 2, 3, 4, 5])

In [8]:
array.shape

(5,)

In [6]:
array.ndim

1

In [7]:
array.size

5

In [16]:
array.shape =[2,3]

In [17]:
array

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
type(array)

numpy.ndarray

In [24]:
#dimentions
a= np.arange(100)

In [25]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [27]:
a.reshape(4,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [33]:
a.reshape(2,5,10)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [8]:
a= np.arange(100).reshape(10,10)

In [9]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [17]:
a[5:7,1:3]

array([[51, 52],
       [61, 62]])

In [37]:
a[4,[1,4]]

array([41, 44])

In [39]:
a[[3,9],[6,3]]

array([36, 93])

In [40]:
a.max()

99

In [41]:
a+a

array([[  0,   2,   4,   6,   8,  10,  12,  14,  16,  18],
       [ 20,  22,  24,  26,  28,  30,  32,  34,  36,  38],
       [ 40,  42,  44,  46,  48,  50,  52,  54,  56,  58],
       [ 60,  62,  64,  66,  68,  70,  72,  74,  76,  78],
       [ 80,  82,  84,  86,  88,  90,  92,  94,  96,  98],
       [100, 102, 104, 106, 108, 110, 112, 114, 116, 118],
       [120, 122, 124, 126, 128, 130, 132, 134, 136, 138],
       [140, 142, 144, 146, 148, 150, 152, 154, 156, 158],
       [160, 162, 164, 166, 168, 170, 172, 174, 176, 178],
       [180, 182, 184, 186, 188, 190, 192, 194, 196, 198]])

In [42]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [54]:
np.exp(np.sqrt(a))

array([[1.00000000e+00, 2.71828183e+00, 4.11325038e+00, 5.65223367e+00,
        7.38905610e+00, 9.35646902e+00, 1.15824352e+01, 1.40940301e+01,
        1.69188287e+01, 2.00855369e+01],
       [2.36243429e+01, 2.75671485e+01, 3.19477455e+01, 3.68019663e+01,
        4.21678207e+01, 4.80856284e+01, 5.45981500e+01, 6.17507194e+01,
        6.95913785e+01, 7.81710163e+01],
       [8.75435125e+01, 9.77658853e+01, 1.08898446e+02, 1.21004958e+02,
        1.34152805e+02, 1.48413159e+02, 1.63861165e+02, 1.80576123e+02,
        1.98641685e+02, 2.18146053e+02],
       [2.39182193e+02, 2.61848047e+02, 2.86246764e+02, 3.12486931e+02,
        3.40682819e+02, 3.70954637e+02, 4.03428793e+02, 4.38238170e+02,
        4.75522407e+02, 5.15428193e+02],
       [5.58109578e+02, 6.03728285e+02, 6.52454039e+02, 7.04464912e+02,
        7.59947674e+02, 8.19098162e+02, 8.82121660e+02, 9.49233295e+02,
        1.02065844e+03, 1.09663316e+03],
       [1.17740461e+03, 1.26323154e+03, 1.35438472e+03, 1.45114748e+03,
   

# numpy excersize udemy

In [209]:
import numpy as np

In [212]:
np.zeros([10,5],dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [19]:
np.ones(10).reshape(2,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [58]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [60]:
np.arange(41)+10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [64]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [65]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [66]:
a= np.arange(10,51)

In [67]:
a[a%2==0]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

# File handling

In [11]:
import os
os.getcwd()

'C:\\Users\\Windows'

In [12]:
os.chdir("C:\\Users\\Windows\\Desktop\\python lab")

In [5]:
new_doc=open("New Text Document.txt")

In [6]:
read_doc=new_doc.read()  #read

In [7]:
print(read_doc)

ab cd


In [24]:
new_doc=open("New Text Documen.txt","a")

In [25]:
new_doc.write(" hello")

6

In [26]:
new_doc.close()

In [37]:
my=open("New Text Documen.txt",'w')            #append

In [38]:
my.write("first")

5

In [39]:
my.close()

In [40]:
my_=open("New Text Documen.txt","a")

In [41]:
my_.write(' second')

7

In [42]:
my_.close()

In [43]:
my__=open("New Text Documen.txt")

In [44]:
my__.read()

'first second'

In [45]:
my__.close()

In [8]:
import shutil           #copy

In [54]:
shutil.copy("New Text Documen.txt","New Text Document.txt")

'New Text Document.txt'

In [62]:
shutil.copy("New Text Documen.txt","C:\\Users\\Windows\\Desktop")

'C:\\Users\\Windows\\Desktop\\New Text Documen.txt'

In [58]:
shutil.copytree("D:\GRE\math_final_videos","D:\GRE\COPIED")

'D:\\GRE\\COPIED'

In [13]:
shutil.move("New Text Documen.txt","C:\\Users\\Windows\\Desktop")

'C:\\Users\\Windows\\Desktop\\New Text Documen.txt'

In [15]:
shutil.move("New Text Documen.txt","C:\\Users\\Windows\\Desktop\\new_file.txt")

'C:\\Users\\Windows\\Desktop\\new_file.txt'

In [5]:
import zipfile

In [6]:
examplezip=zipfile.ZipFile("D:/SOFT/ExpressPCBsetup7_4_1.zip")            #zip

In [7]:
examplezip.namelist()

['ExpressPCBsetup7_4_1.exe']

# ROUTINES

In [9]:
import numpy as np

In [28]:
n=np.empty([3,2],dtype=int)

In [29]:
n

array([[       110,          0],
       [ 538976288, 1953723754],
       [1701344288, 1869770784]])

In [37]:
n=np.zeros([1,2],dtype=int)
n

array([[0, 0]])

In [40]:
np.eye(1,3,2)

array([[0., 0., 1.]])

In [43]:
np.eye(1)

array([[1.]])

In [46]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [47]:
x = np.array([[1,2],[3,4],[5,6]])

y = np.asmatrix(x)
print(y)

[[1 2]
 [3 4]
 [5 6]]


In [49]:
#np.full(shape, fill_value)

x = np.full(shape=(2,3), fill_value=7)
print(x)

[[7 7 7]
 [7 7 7]]


In [52]:
s=np.arange(12).reshape(3,4)
s

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
s.ravel()      # AND MANY MORE FUNCTIONS LIKE X.T, TRANSPOSE, SPLIT, INSERT

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [67]:
b=np.asarray(s)
b
np.split(b,[0,2],1)

[array([], shape=(3, 0), dtype=int32), array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [71]:
s
np.insert(s,1,87,1)

array([[ 0, 87,  1,  2,  3],
       [ 4, 87,  5,  6,  7],
       [ 8, 87,  9, 10, 11]])

In [74]:
np.stack([s,s],axis=1)

array([[[ 0,  1,  2,  3],
        [ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [ 8,  9, 10, 11]]])

# PANDAS

In [158]:
import numpy as np
import pandas as pd

In [82]:
print("""array formation
    -dictionary
    -ndarray
    -scalar values like 1,2,3""")

array formation
    -dictionary
    -ndarray
    -scalar values like 1,2,3


In [86]:
data = np.array(['Apple', 'Mango', 'Orange'])
data
pd.Series(data)

0     Apple
1     Mango
2    Orange
dtype: object

In [87]:
data1 = np.array(['Aditya', 'Vamshi', 'Kranthi'])
s1 = pd.Series(data1, index=[101, 102, 103])
print(s1)

101     Aditya
102     Vamshi
103    Kranthi
dtype: object


In [90]:
#data2 = {'a':0, 'b':1, 'c':2, 'd':3, 'e':4}
s2 = pd.Series({'a':0, 'b':1, 'c':2, 'd':3, 'e':4})
s2

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [91]:
data3 = {'a':0, 'b':1, 'c':2, 'd':3, 'e':4}
s3 = pd.Series(data3, index=['x', 'y', 'z', 'a', 'b'])
print(s3)

x    NaN
y    NaN
z    NaN
a    0.0
b    1.0
dtype: float64


In [96]:
s = pd.Series(2, index=[0,1,2,3,4])
print(s)

0    2
1    2
2    2
3    2
4    2
dtype: int64


In [97]:
s[3]

2

In [104]:
print(s[[0,3]])

0    2
3    2
dtype: int64


# DATAFRAME OPERATION 3

In [106]:
"""pandas dataframe can be created by;
   -Lists
   -dictionary
   -Series
   -Numpy ndarrays"""

'pandas dataframe\n   -Lists\n   -dictionary\n   -Series\n   -Numpy ndarrays'

In [111]:
df=pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [112]:
lst1 = [1,2,3,4,5]
df2 = pd.DataFrame(lst1)
print(df2)

   0
0  1
1  2
2  3
3  4
4  5


In [114]:
df3 = pd.DataFrame(lst1, index = ['a','b','c','d','e'],columns=["cl"])
print(df3)

   cl
a   1
b   2
c   3
d   4
e   5


In [117]:
lst2 = [['Amar', 30], ['Akbar', 31], ['Anthony', 32]]
df5 = pd.DataFrame(lst2, index = ['Emp1', 'Emp2','Emp3'], columns =
['Emp_Name', 'Age'])
df5

Emp_Name  Age
Emp1     Amar   30
Emp2    Akbar   31
Emp3  Anthony   32

In [119]:
data = {'Name':['Tom', 'Jack', 'Steve', 'Ricky'], 'Age':[28,34,29,42]}
df6 = pd.DataFrame(data)
print(df6)

    Name  Age
0    Tom   28
1   Jack   34
2  Steve   29
3  Ricky   42


In [121]:
data = {'Name':['Tom', 'Jack', 'Steve', 'Ricky'],'Age':[28,34,29,42]}                             #USNING ARRAYS
df7 = pd.DataFrame(data, index=['rank1','rank2','rank3','rank4'])
print(df7)

        Name  Age
rank1    Tom   28
rank2   Jack   34
rank3  Steve   29
rank4  Ricky   42


In [124]:
data = [{'a': 1, 'b': 2}, {'a': 5, 'b': 10, 'c': 20}]                                                #USNING DICTIONARY
df7 = pd.DataFrame(data)
df7

a   b     c
0  1   2   NaN
1  5  10  20.0

In [128]:
data = [{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 20}]
#With two column indices, values same as dictionary keys
df9 = pd.DataFrame(data, index=['first', 'second'], columns=['a', 'b'])
df9

a   b
first   1   2
second  5  10

In [130]:
d = {'one':pd.Series([1, 2, 3], index=['a', 'b', 'c']),
'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df11 = pd.DataFrame(d)
df11

one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [131]:
dff={'one' :pd.Series([1,2,3],index=['one','two','three']),
    'two' :pd.Series([1,2,3],index=['one','two','three'])}

In [78]:
grades = [76,95,77,78,99]
bsdegrees = [1,1,0,0,1]
msdegrees = [2,1,0,0,0]
phddegrees = [0,1,0,0,0]

In [79]:
material=zip(grades,bsdegrees,msdegrees,phddegrees)

In [80]:
df=pd.DataFrame(material)

TypeError: data argument can't be an iterator

In [ ]:
list1=[['one',1],['two',2],['three',3]]

In [32]:
pd.DataFrame(list1,index=[1,2,3],columns=['words','number'])

words  number
1    one       1
2    two       2
3  three       3

In [151]:
df = pd.DataFrame({'userid':[1,1,1,1, 2,2,2],
'itemid':[1,1,3,4, 1,2,3] })

In [152]:
df

userid  itemid
0       1       1
1       1       1
2       1       3
3       1       4
4       2       1
5       2       2
6       2       3

In [166]:
df.drop_duplicates()

userid  itemid
0       1       1
2       1       3
3       1       4
4       2       1
5       2       2
6       2       3

In [170]:
print(df.drop_duplicates(inplace=True))

None


In [24]:
df = pd.DataFrame(data=np.array([[1, 2, 3], [1, 2, 3], [7, 8, 9], [40, 50, 60], [23, 35, 37]]),
index= [2.5, 12.6, 4.8, 4.8, 2.5],
columns=[48, 49, 50])

In [25]:
df.drop_duplicates(inplace=True)

In [27]:
df.reset_index(inplace=True)

In [28]:
df

index  48  49  50
0    2.5   1   2   3
1    4.8   7   8   9
2    4.8  40  50  60
3    2.5  23  35  37

In [184]:
print(df.rename(columns={48:'a',49:'b',50:'c'},inplace=True))

None


In [189]:
df

index  48  49  50
0    2.5   1   2   3
1    4.8   7   8   9
2    4.8  40  50  60
3    2.5  23  35  37

# DATAFRAME OPERATION 1

In [237]:
x = {'one' : pd.Series([1, 2, 3], index=['a','b','c']),
     'two' : pd.Series([1, 2, 3, 4], index=['a','b','c','d'])}
df = pd.DataFrame(x)

In [192]:
df

one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [225]:
df['one']

a    1.0
b    2.0
c    3.0
d    NaN
Name: one, dtype: float64

In [194]:
df['three']=df['one']+df['two']*2

In [238]:
df['four']=pd.Series([1,2,3,4],index=['a','b','d','c'])

In [222]:
df

one  three
a  1.0    3.0
b  2.0    6.0
c  3.0    9.0
d  NaN    NaN

In [239]:
del(df['four'])                                #DEL is only for columns,for rows DROP is used

In [206]:
df.pop('two')

a    1
b    2
c    3
d    4
Name: two, dtype: int64

# Row operation

In [214]:
"""Rows in a Dataframe can be selected in two ways:
   (1) row label ; (2) integer location"""

In [216]:
df.loc['a']

one      1.0
three    3.0
Name: a, dtype: float64

In [217]:
df.iloc[1]

one      2.0
three    6.0
Name: b, dtype: float64

In [218]:
df1 = pd.DataFrame([[1, 2], [3, 4]], columns=['a','b'])
df2 = pd.DataFrame([[5, 6], [7, 8]], columns=['a','b'])
df1 = df1.append(df2)

In [219]:
df1

a  b
0  1  2
1  3  4
0  5  6
1  7  8

In [227]:
df[0:2]                                              #slicing only available for rows hence no need of loc or iloc

one  three
a  1.0    3.0
b  2.0    6.0

In [234]:
df.drop('a')                                         #deletion can only be done by name

one  three
b  2.0    6.0
c  3.0    9.0
d  NaN    NaN

# DATAFRAME OPERATION 2

In [240]:
x = {'one' : pd.Series([1, 2, 3], index=['a','b','c']),
     'two' : pd.Series([1, 2, 3, 4], index=['a','b','c','d'])}
df = pd.DataFrame(x)

In [248]:
def multiplication(val1):
    return val1*2

In [249]:
df.pipe(multiplication)

one  two
a  2.0    2
b  4.0    4
c  6.0    6
d  NaN    8

In [250]:
def mul10(val1,val2):
    return val1*val2
df.pipe(mul10,5)

one  two
a   5.0    5
b  10.0   10
c  15.0   15
d   NaN   20

In [258]:
df.iloc[3].apply(np.mean)

one    NaN
two    4.0
Name: d, dtype: float64

In [260]:
df.apply(np.mean,axis=1)

a    1.0
b    2.0
c    3.0
d    4.0
dtype: float64

In [265]:
df2 = df.apply(lambda x: x.max() - x.min(),axis=1)

In [266]:
df2

a    0.0
b    0.0
c    0.0
d    0.0
dtype: float64

In [267]:
df2 = df.applymap(lambda p: p*10)

In [268]:
df2

one  two
a  10.0   10
b  20.0   20
c  30.0   30
d   NaN   40

In [270]:
df2 = df.mul([10, 100,4,3], axis=0)

In [271]:
df2

one    two
a   10.0   10.0
b  200.0  200.0
c   12.0   12.0
d    NaN   12.0

In [272]:
df2 = pd.DataFrame([[4,4], [4,4]], index = ['p','q'], columns = ['c','d'])
print(df2)

   c  d
p  4  4
q  4  4


In [273]:
df1 = pd.DataFrame([[4,4], [4,4]], index = ['p','q'], columns = ['c','d'])
print(df1)

   c  d
p  4  4
q  4  4


In [274]:
pd.np.multiply(df1,df2)

c   d
p  16  16
q  16  16

In [277]:
df.loc[2] = [11, 12]                           #Row creation

In [278]:
df

one  two
a   1.0    1
b   2.0    2
c   3.0    3
d   NaN    4
2  11.0   12

In [279]:
df.iloc[2] = [11, 12]                                 #Row editing

In [280]:
df

one  two
a   1.0    1
b   2.0    2
c  11.0   12
d   NaN    4
2  11.0   12

In [281]:
df=pd.DataFrame(data=[[1,2],[3,4],[1,2],[1,4],[1,2]],columns=['col1','col2'])
print(df)

   col1  col2
0     1     2
1     3     4
2     1     2
3     1     4
4     1     2


In [286]:
df.duplicated(keep="last")

0     True
1    False
2     True
3    False
4    False
dtype: bool

In [287]:
names = ['a','b','c','d','d']
grades = [76,-2,77,78,101]

In [288]:
d=pd.DataFrame([names,grades])

In [293]:
d

0   1   2   3    4
0   a   b   c   d    d
1  76  -2  77  78  101

In [297]:
d.iloc[0]=[1,4,2,1,8]
d

0  1   2   3    4
0   1  4   2   1    8
1  76 -2  77  78  101

In [309]:
d.loc[(d[1]>0)]=100

In [310]:
d

0    1    2    3    4      1      9
0  100  100  100  100  100  100.0  100.0
1   76   -2   77   78  101    NaN    NaN

In [311]:
d.loc[(d[1]>0)]

0    1    2    3    4      1      9
0  100  100  100  100  100  100.0  100.0

In [314]:
d[d[2]==77]=100

In [315]:
d

0    1    2    3    4      1      9
0  100  100  100  100  100  100.0  100.0
1  100  100  100  100  100  100.0  100.0

In [316]:
d[d[2]==100]

0    1    2    3    4      1      9
0  100  100  100  100  100  100.0  100.0
1  100  100  100  100  100  100.0  100.0

In [318]:
from numpy.random import randn
np.random.seed(101)

df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())


In [319]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [330]:
df[df['W']<0]

W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

In [326]:
df[df['W']>0]


W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

# CSV EXCEL etc

In [331]:
import os

In [347]:
os.getcwd()
os.chdir("D:\DOWNLOADS\DATA SCIENCE\datasets\datasets")
os.getcwd()

'D:\\DOWNLOADS\\DATA SCIENCE\\datasets\\datasets'

In [350]:
location="D:/DOWNLOADS/DATA SCIENCE/datasets/datasets/axisdata.csv"

In [352]:
df=pd.read_csv(location)
df.head()

Fname      Lname Gender  Hours Worked SalesTraining  Years Experience  \
0     Jada   Walters       F            39             N                 3   
1   Nicole  Henderson      F            46             N                 3   
2    Tanya      Moore      F            42             Y                 4   
3  Ronelle    Jackson      F            38             Y                 5   
4     Brad      Sears      M            33             N                 4   

   Cars Sold  
0          2  
1          6  
2          6  
3          3  
4          2

In [353]:
df.mean()

Hours Worked        33.727728
Years Experience     3.026026
Cars Sold            3.922923
dtype: float64

In [354]:
df.describe()

Hours Worked  Years Experience   Cars Sold
count    999.000000        999.000000  999.000000
mean      33.727728          3.026026    3.922923
std        8.223454          1.394709    1.527000
min       20.000000          1.000000    1.000000
25%       27.000000          2.000000    3.000000
50%       34.000000          3.000000    4.000000
75%       41.000000          4.000000    5.000000
max       48.000000          5.000000    7.000000

In [20]:
import pandas as pd                                #exporting csv

In [21]:
names='Bob Jessica Mary John Mel'.split()

In [22]:
grades='76 45 43 21 67'.split()
GradeZip=zip(names,grades)

In [24]:
df= pd.DataFrame(list(GradeZip))

In [25]:
df

0   1
0      Bob  76
1  Jessica  45
2     Mary  43
3     John  21
4      Mel  67

In [26]:
import os
os.getcwd()

'C:\\Users\\Windows'

In [29]:
os.chdir('C://Users//Windows/Desktop/')

In [30]:
os.getcwd()

'C:\\Users\\Windows\\Desktop'

In [38]:
df.to_csv('C:/Users/Windows/Desktop/filecsv.csv',header=False)

In [37]:
df= pd.read_excel('D:\\DOWNLOADS\\DATA SCIENCE\\datasets\\datasets\\algebradata.xlsx') # EXCEL IMPORT

In [35]:
df.head()

Fname     Lname Gender Grade  Hours of Study
0     Mary  Ettienne      F     B              16
1  Charles    Looner      M     F               8
2    Betty  Franklin      F     A              24
3    Roger   Withers      M     C               5
4     John   Mulgrew      M     A               5

In [44]:
df.to_excel('C:\\Users\\Windows\\Desktop\\theexcelfile.xlsx',sheet_name='sheet2')         #EXPORTING single EXCEL

In [47]:
df = pd.DataFrame(list(GradeZip), columns=['Names','Grades'])

In [48]:
df

Empty DataFrame
Columns: [Names, Grades]
Index: []

In [49]:
df2 = pd.DataFrame(list(GradeZip), columns=['Names','Grades'])

In [50]:
df2

Empty DataFrame
Columns: [Names, Grades]
Index: []

In [51]:
writer=pd.ExcelWriter('D:\\DOWNLOADS\\DATA SCIENCE\\datasets\\datasets\\algebradata.xlsx',engine="xlsxwriter") #for multiple excel exports

In [52]:
df.to_excel(writer,"Sheet_1")
df2.to_excel(writer,"Sheet_1")

In [53]:
writer.save()

In [59]:
import glob

In [82]:
os.getcwd()

'C:\\Users\\Windows\\Desktop'

In [84]:
all_data=pd.DataFrame()     # combining excel files using glob

for x in glob.glob('D:\DOWNLOADS\DATA SCIENCE\datasets\datasets\weekly_call_data\weekdata_*.xlsx'):
    df =pd.read_excel(x)
    all_data=all_data.append(df,ignore_index=True)

In [85]:
all_data.tail()

CallingNumber DayOfWeek TimeOfDay  CallDuration      ReasonForCall  \
129583  420-535-7591       mon     09:34            23    Product Inquiry   
129584  351-682-2460       wed     10:11             9          Complaint   
129585  143-883-4281       wed     10:26             3  Technical Support   
129586  847-303-7391       tue     14:28            24             Return   
129587  365-513-5324       mon     15:09             2    Product Inquiry   

       AnsweringAgent  
129583          David  
129584          Maria  
129585           Lisa  
129586         Roland  
129587        Kennedy

In [74]:
print(all_data)

Empty DataFrame
Columns: []
Index: []


In [76]:
import pandas as pd              #DATAFRAME FROM RANDOM VALUES
from numpy import random
from numpy.random import randint

In [95]:
#names = ['Bob','Jessica','Mary','John','Mel']
randnames = [] 
for i in range(1000):
    name = names[randint(low=0, high=len(names))]
    randnames.append(name)                                            

In [96]:
births = []
for i in range(1000):
    births.append(randint(low=0, high=1000))


In [99]:
Babydataset = list(zip(randnames, births))
df = pd.DataFrame(data = Babydataset, columns=['Names', 'Births'])
df.head()

Names  Births
0   Bob     942
1  John     714
2   Mel     969
3  John     342
4   Bob     338

# CREATING NEW VARIABLES

In [3]:
import numpy as np
import pandas as pd


In [33]:
df=pd.read_csv('D:\\DOWNLOADS\\DATA SCIENCE\\datasets\\datasets\\algebradata.csv')

In [34]:
df.head()

Fname     Lname Gender Grade  Hours of Study
0     Mary  Ettienne      F     B              16
1  Charles    Looner      M     F               8
2    Betty  Franklin      F     A              24
3    Roger   Withers      M     C               5
4     John   Mulgrew      M     A               5

In [121]:
df['Hours of Study'].describe()

count    999.000000
mean      15.115115
std        8.991187
min        0.000000
25%        7.000000
50%       15.000000
75%       23.000000
max       30.000000
Name: Hours of Study, dtype: float64

In [120]:
df['Hours of Study'].min()

0

In [7]:
bins=[0,5,10,15,20,25,30]
grouping_name='F E D C B A'.split()

In [8]:
df['letter grade']=pd.cut(df['Hours of Study'],bins,labels=grouping_name)

In [140]:
dff=df[0:5]

In [141]:
dff

Fname     Lname Gender Grade  Hours of Study letter grade
0     Mary  Ettienne      F     B              16            C
1  Charles    Looner      M     F               8            E
2    Betty  Franklin      F     A              24            B
3    Roger   Withers      M     C               5            F
4     John   Mulgrew      M     A               5            F

In [12]:
pd.value_counts(df['letter grade'])

A    175
D    175
C    162
F    162
B    149
E    143
Name: letter grade, dtype: int64

In [19]:
bins=[0,15,30]
status=['fail','pass']

In [20]:
df['status_p_f']=pd.cut(df['Hours of Study'],bins,labels=status)

In [22]:
df.head()

Fname     Lname Gender Grade  Hours of Study letter grade status_p_f
0     Mary  Ettienne      F     B              16            C       pass
1  Charles    Looner      M     F               8            E       fail
2    Betty  Franklin      F     A              24            B       pass
3    Roger   Withers      M     C               5            F       fail
4     John   Mulgrew      M     A               5            F       fail

In [23]:
pd.value_counts(df['status_p_f'])

pass    486
fail    480
Name: status_p_f, dtype: int64

# Group by

In [24]:
import pandas as pd

In [51]:
df=pd.DataFrame({'A':['foo','bar','foo','bar','foo','candy'],
                 'B':['one','two','three','one','three','two'],
                 'C':np.random.randn(6),
                 'D':np.random.randn(6)})

In [43]:
df

A      B         C         D
1    foo    one  2.486892 -0.508783
2    bar    two  1.031337 -0.610913
1    foo  three -0.239719 -1.017730
2    bar    one  0.163809  0.000879
1    foo  three  1.286851 -0.354785
2  candy    two  1.137203 -1.107887

In [40]:
grouped=df.groupby('A')
print(grouped)

In [38]:
grouped = df.groupby(['A', 'B'])
print(grouped)

In [41]:
df

A      B         C         D
0    foo    one -0.662961 -0.909283
1    bar    two -0.107246 -0.786643
2    foo  three -0.512840 -0.026111
3    bar    one -0.337893  0.150412
4    foo  three -1.173615  1.223590
5  candy    two  0.527380  0.758766

In [45]:
g=df.groupby(level=0)

In [49]:
print(g.first())

     A    B         C         D
1  foo  one  2.486892 -0.508783
2  bar  two  1.031337 -0.610913


In [50]:
print(g.last())

       A      B         C         D
1    foo  three  1.286851 -0.354785
2  candy    two  1.137203 -1.107887


In [56]:
df.groupby(['A']).sum()

C         D
A                        
bar    0.208982 -1.630717
candy -0.036392 -1.352942
foo   -1.030541  5.373398

In [3]:
df=pd.read_csv('D:\\DOWNLOADS\\DATA SCIENCE\\datasets\\datasets\\algebradata.csv')

In [4]:
df.head()

Fname     Lname Gender Grade  Hours of Study
0     Mary  Ettienne      F     B              16
1  Charles    Looner      M     F               8
2    Betty  Franklin      F     A              24
3    Roger   Withers      M     C               5
4     John   Mulgrew      M     A               5

In [73]:
df.groupby(['Gender']).sum()

Hours of Study
Gender                
F                 8115
M                 6985

In [76]:
dfnew=df.groupby(['Gender']).sum()
type(dfnew)

pandas.core.frame.DataFrame

In [83]:
f_hour=dfnew['Hours of Study'][0]
m_hour=dfnew['Hours of Study'][1]

In [84]:
f_count=pd.value_counts(df['Gender'])[0]
m_count=pd.value_counts(df['Gender'])[1]

In [85]:
if (f_hour/f_count)>(m_hour/m_count):
    print('female are more hardworking')
else:
    print('male are more hardworking')

female are more hardworking


In [88]:
df.groupby(['Gender'],sort=False).sum()

Hours of Study
Gender                
F                 8115
M                 6985

In [90]:
df.groupby(['Gender']).get_group('F').head()

Fname     Lname Gender Grade  Hours of Study
0    Mary  Ettienne      F     B              16
2   Betty  Franklin      F     A              24
5    Jada  Isaacson      F     C              30
7  August    Carter      F     C              11
8   Karen    Looner      F     A              12

In [94]:
df.groupby('Gender').groups     #GroupBy object attributes

{'F': Int64Index([  0,   2,   5,   7,   8,  10,  11,  12,  15,  18,
             ...
             979, 980, 982, 987, 989, 990, 992, 995, 997, 998],
            dtype='int64', length=518),
 'M': Int64Index([  1,   3,   4,   6,   9,  13,  14,  16,  17,  19,
             ...
             981, 983, 984, 985, 986, 988, 991, 993, 994, 996],
            dtype='int64', length=481)}

In [98]:
record=df.duplicated(['Fname','Lname'])

In [99]:
pd.value_counts(record)

False    667
True     332
dtype: int64

In [109]:
df['Full']=df['Fname']+[" "]+df['Lname']
df.groupby('Full').groups

{'Aaron Adams': Int64Index([845], dtype='int64'),
 'Aaron Carter': Int64Index([396], dtype='int64'),
 'Aaron Davidson': Int64Index([573], dtype='int64'),
 'Aaron Ettienne': Int64Index([914, 964], dtype='int64'),
 'Aaron Franklin': Int64Index([586], dtype='int64'),
 'Aaron Harrison': Int64Index([195], dtype='int64'),
 'Aaron Henderson': Int64Index([249], dtype='int64'),
 'Aaron Isaacson': Int64Index([265], dtype='int64'),
 'Aaron Jackson': Int64Index([88], dtype='int64'),
 'Aaron Johnson': Int64Index([775], dtype='int64'),
 'Aaron Kennedy': Int64Index([32], dtype='int64'),
 'Aaron Looner': Int64Index([401], dtype='int64'),
 'Aaron Martins': Int64Index([330], dtype='int64'),
 'Aaron Patterson': Int64Index([656], dtype='int64'),
 'Aaron Samuelson': Int64Index([921], dtype='int64'),
 'Aaron Turner': Int64Index([157, 163, 535], dtype='int64'),
 'Aaron Walters ': Int64Index([19, 848], dtype='int64'),
 'Aaron Withers': Int64Index([400], dtype='int64'),
 'Adam Baker': Int64Index([885], dtype='

In [ ]:
list(filter(fun,seq))

# Groupby multi-indexing

In [113]:
arrays = [['bar', 'bar', 'baz', 'baz', 'foo', 'foo', 'qux', 'qux'], ['one', 'two', 'one', 'two', 'one', 'two', 'one', 'two']]

In [114]:
index=pd.MultiIndex.from_arrays(arrays,names=['first','second'])

In [118]:
s=pd.Series(np.random.randn(8),index=index)
s

first  second
bar    one      -0.694833
       two      -1.820561
baz    one      -0.700858
       two      -0.823872
foo    one      -1.026065
       two      -0.183023
qux    one       1.481013
       two       0.976481
dtype: float64

In [121]:
s.groupby(level=1).sum()

second
one   -0.940743
two   -1.850974
dtype: float64

In [122]:
s.sum(level=1)

second
one   -0.940743
two   -1.850974
dtype: float64

In [123]:
print(s.groupby(level=['first', 'second']).sum())

first  second
bar    one      -0.694833
       two      -1.820561
baz    one      -0.700858
       two      -0.823872
foo    one      -1.026065
       two      -0.183023
qux    one       1.481013
       two       0.976481
dtype: float64


In [126]:
s.groupby([pd.Grouper(level=1), 'first']).sum()

second  first
one     bar     -0.694833
        baz     -0.700858
        foo     -1.026065
        qux      1.481013
two     bar     -1.820561
        baz     -0.823872
        foo     -0.183023
        qux      0.976481
dtype: float64

# Aggregation

In [8]:
import numpy as np
import pandas as pd

In [7]:
df.head()

Fname     Lname Gender Grade  Hours of Study
0     Mary  Ettienne      F     B              16
1  Charles    Looner      M     F               8
2    Betty  Franklin      F     A              24
3    Roger   Withers      M     C               5
4     John   Mulgrew      M     A               5

In [11]:
grp=df.groupby('Gender')
print(grp.agg(np.sum))

        Hours of Study
Gender                
F                 8115
M                 6985


In [17]:
group=df.groupby(['Gender','Grade'])
print(group.aggregate(np.mean))

              Hours of Study
Gender Grade                
F      A           18.904762
       B           15.919643
       C           14.386139
       D           14.044248
       F            4.833333
M      A           16.664062
       B           15.860465
       C           14.093750
       D           15.116071
       F            7.491525


In [23]:
group=df.groupby(['Gender','Grade'],as_index=False)
print(group.aggregate(np.mean))

  Gender Grade  Hours of Study
0      F     A       18.904762
1      F     B       15.919643
2      F     C       14.386139
3      F     D       14.044248
4      F     F        4.833333
5      M     A       16.664062
6      M     B       15.860465
7      M     C       14.093750
8      M     D       15.116071
9      M     F        7.491525


In [20]:
print(df.groupby(['Gender','Grade'], as_index=False).mean())

  Gender Grade  Hours of Study
0      F     A       18.904762
1      F     B       15.919643
2      F     C       14.386139
3      F     D       14.044248
4      F     F        4.833333
5      M     A       16.664062
6      M     B       15.860465
7      M     C       14.093750
8      M     D       15.116071
9      M     F        7.491525


In [37]:
grouped=df.groupby(['Gender','Grade'])
print(grouped.size())

Gender  Grade
F       A        168
        B        112
        C        101
        D        113
        F         24
M       A        128
        B         86
        C         96
        D        112
        F         59
dtype: int64


In [54]:
grouped=df.groupby(['Gender','Grade'])
print(grouped.count())

              Fname  Lname  Hours of Study
Gender Grade                              
F      A        168    168             168
       B        112    112             112
       C        101    101             101
       D        113    113             113
       F         24     24              24
M      A        128    128             128
       B         86     86              86
       C         96     96              96
       D        112    112             112
       F         59     59              59


In [53]:
grouped.describe()

Hours of Study                                                 
                count       mean       std  min  25%   50%   75%   max
Gender                                                                
F               518.0  15.666023  8.952618  0.0  9.0  15.0  23.0  30.0
M               481.0  14.521830  9.004168  0.0  7.0  15.0  22.0  30.0

### aggregate funtion
mean()
sum()
size()
count()
std()
var()
sem()
describe()
first()
last()
nth()
min()
max()

In [41]:
print(grouped['Hours of Study'].agg([np.sum, np.mean, np.std]))

               sum       mean       std
Gender Grade                           
F      A      3176  18.904762  7.641079
       B      1783  15.919643  9.069440
       C      1453  14.386139  8.954295
       D      1587  14.044248  9.122568
       F       116   4.833333  2.713359
M      A      2133  16.664062  9.317055
       B      1364  15.860465  8.613482
       C      1353  14.093750  9.187037
       D      1693  15.116071  8.535823
       F       442   7.491525  5.516036


In [48]:
grouped=df.groupby('Gender')
print(grouped['Hours of Study'].agg([np.sum,np.mean,np.std,np.var,np.min,np.max,np.size]))

         sum       mean       std        var  amin  amax  size
Gender                                                        
F       8115  15.666023  8.952618  80.149366     0    30   518
M       6985  14.521830  9.004168  81.075043     0    30   481


In [51]:
print((grouped.agg([np.sum, np.mean, np.std])
       .rename(columns={'sum': 'foo', 'mean': 'bar', 'std': 'baz'})))


       Hours of Study                     
                  foo        bar       baz
Gender                                    
F                8115  15.666023  8.952618
M                6985  14.521830  9.004168


In [ ]:
grouped = df.groupby('A')
print(grouped.agg({'C' : np.sum,'D' : lambda x: np.std(x, ddof=1)}))

# MERGE

In [100]:
import numpy as np
import pandas as pd

In [64]:
left_df=pd.DataFrame(data=[[0,'one'],[1,'two'],[2,'three'],[3,'four']],columns=['id','left_side'],index=None)

In [82]:
left_df.set_index('id',inplace=True)
left_df


left_side
id          
0        one
1        two
2      three
3       four

In [63]:
right_df=pd.DataFrame(data=[[0,'oneone'],[1,'twotwo'],[0,'threethree'],[3,'fourfour']],columns=['id','right_side'],index=None)
right_df

id  right_side
0   0      oneone
1   1      twotwo
2   0  threethree
3   3    fourfour

In [68]:
pd.merge(left=left_df,right=right_df,on='id',how='left')    #left merge

id left_side  right_side
0   0       one      oneone
1   0       one  threethree
2   1       two      twotwo
3   2     three         NaN
4   3      four    fourfour

In [101]:
df1=pd.DataFrame({'HPI':[80,85,88,85],
                 'Int_rate':[2,3,2,2],
                 'US_GDP_Thousands':[50,55,65,55]},
                 index=[2001,2002,2003,2004])
df2=pd.DataFrame({'HPI':[80,85,88,85],
                  'Int_rate':[2,3,2,2],
                  'US_GDP_Thousands':[50,55,65,55]},
                 index=[2005,2006,2007,2008])
df3=pd.DataFrame({'HPI':[80,85,88,85],
                  'Int_rate':[7,8,9,6],
                  'Low_tier_HPI':[50,52,50,53]},
                 index=[2001,2002,2003,2004])

In [102]:
print(df1)
print(df2)
print(df3)

      HPI  Int_rate  US_GDP_Thousands
2001   80         2                50
2002   85         3                55
2003   88         2                65
2004   85         2                55
      HPI  Int_rate  US_GDP_Thousands
2005   80         2                50
2006   85         3                55
2007   88         2                65
2008   85         2                55
      HPI  Int_rate  Low_tier_HPI
2001   80         7            50
2002   85         8            52
2003   88         9            50
2004   85         6            53


In [103]:
pd.merge(df1,df2,on=['HPI'])

HPI  Int_rate_x  US_GDP_Thousands_x  Int_rate_y  US_GDP_Thousands_y
0   80           2                  50           2                  50
1   85           3                  55           3                  55
2   85           3                  55           2                  55
3   85           2                  55           3                  55
4   85           2                  55           2                  55
5   88           2                  65           2                  65

In [104]:
pd.merge(df1,df2,on=['HPI','Int_rate'])

HPI  Int_rate  US_GDP_Thousands_x  US_GDP_Thousands_y
0   80         2                  50                  50
1   85         3                  55                  55
2   88         2                  65                  65
3   85         2                  55                  55

In [105]:
merge_13=pd.merge(df1,df3,on='HPI')

In [106]:
merge_13.set_index('HPI',inplace=True)

In [108]:
print(merge_13)

     Int_rate_x  US_GDP_Thousands  Int_rate_y  Low_tier_HPI
HPI                                                        
80            2                50           7            50
85            3                55           8            52
85            3                55           6            53
85            2                55           8            52
85            2                55           6            53
88            2                65           9            50


In [109]:
df1 = pd.DataFrame({                                  #redefine dataframes df1 and df3
                    'Int_rate':[2, 3, 2, 2],
                    'US_GDP_Thousands':[50, 55, 65, 55],
                    'Year':[2001, 2002, 2003, 2004]
                    })

df3 = pd.DataFrame({
                    'Unemployment':[7, 8, 9, 6],
                    'Low_tier_HPI':[50, 52, 50, 53],
                    'Year':[2001, 2003, 2004, 2005]})


In [110]:
merged = pd.merge(df1,df3, on='Year')
print(merged)

   Int_rate  US_GDP_Thousands  Year  Unemployment  Low_tier_HPI
0         2                50  2001             7            50
1         2                65  2003             8            52
2         2                55  2004             9            50


In [112]:
merged = pd.merge(df1,df3, on='Year')           #making year as index
merged.set_index('Year', inplace=True)          #Notice how 2005 and 2002 are just totally missing?
print(merged)                                  #Merge will natively just merge existing/shared data.                       

      Int_rate  US_GDP_Thousands  Unemployment  Low_tier_HPI
Year                                                        
2001         2                50             7            50
2003         2                65             8            52
2004         2                55             9            50


In [113]:
merged = pd.merge(df1,df3, on='Year', how='left')    #similary for right outer inner(which is default)
merged.set_index('Year', inplace=True)
print(merged)

      Int_rate  US_GDP_Thousands  Unemployment  Low_tier_HPI
Year                                                        
2001         2                50           7.0          50.0
2002         3                55           NaN           NaN
2003         2                65           8.0          52.0
2004         2                55           9.0          50.0


# JOINING

In [114]:
df1.set_index('Year', inplace=True)
df3.set_index('Year', inplace=True)
joined = df1.join(df3, how="outer")
print(joined)

      Int_rate  US_GDP_Thousands  Unemployment  Low_tier_HPI
Year                                                        
2001       2.0              50.0           7.0          50.0
2002       3.0              55.0           NaN           NaN
2003       2.0              65.0           8.0          52.0
2004       2.0              55.0           9.0          50.0
2005       NaN               NaN           6.0          53.0


# CONCATENATION AND APPENDING

In [115]:
df1 = pd.DataFrame({'HPI':[80,85,88,85],
                                'Int_rate':[2, 3, 2, 2],
                                'US_GDP_Thousands':[50, 55, 65, 55]},
                                index = [2001, 2002, 2003, 2004])

df2 = pd.DataFrame({'HPI':[80,85,88,85],
                                'Int_rate':[2, 3, 2, 2],
                                'US_GDP_Thousands':[50, 55, 65, 55]},
                                index = [2005, 2006, 2007, 2008])

df3 = pd.DataFrame({'HPI':[80,85,88,85],
                                'Int_rate':[2, 3, 2, 2],
                                'Low_tier_HPI':[50, 52, 50, 53]},
                                index = [2001, 2002, 2003, 2004])

In [116]:
Concat_1_2 = pd.concat([df1, df2])
print(Concat_1_2)

      HPI  Int_rate  US_GDP_Thousands
2001   80         2                50
2002   85         3                55
2003   88         2                65
2004   85         2                55
2005   80         2                50
2006   85         3                55
2007   88         2                65
2008   85         2                55


In [124]:
Concat_1_3 = pd.concat([df1, df3])
print(Concat_1_3)

      HPI  Int_rate  Low_tier_HPI  US_GDP_Thousands
2001   80         2           NaN              50.0
2002   85         3           NaN              55.0
2003   88         2           NaN              65.0
2004   85         2           NaN              55.0
2001   80         2          50.0               NaN
2002   85         3          52.0               NaN
2003   88         2          50.0               NaN
2004   85         2          53.0               NaN


C:\Users\Windows\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


In [121]:
Concat_1_2_3 = pd.concat([df1,df2,df3])
print(Concat_1_2_3)

      HPI  Int_rate  Low_tier_HPI  US_GDP_Thousands
2001   80         2           NaN              50.0
2002   85         3           NaN              55.0
2003   88         2           NaN              65.0
2004   85         2           NaN              55.0
2005   80         2           NaN              50.0
2006   85         3           NaN              55.0
2007   88         2           NaN              65.0
2008   85         2           NaN              55.0
2001   80         2          50.0               NaN
2002   85         3          52.0               NaN
2003   88         2          50.0               NaN
2004   85         2          53.0               NaN


C:\Users\Windows\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


In [122]:
Append_1_2 = df1.append(df2)                    #APPENDING
print(Append_1_2)

      HPI  Int_rate  US_GDP_Thousands
2001   80         2                50
2002   85         3                55
2003   88         2                65
2004   85         2                55
2005   80         2                50
2006   85         3                55
2007   88         2                65
2008   85         2                55


In [123]:
Append_1_3 = df1.append(df3)                            #SAME INDEX
print(Append_1_3)

      HPI  Int_rate  Low_tier_HPI  US_GDP_Thousands
2001   80         2           NaN              50.0
2002   85         3           NaN              55.0
2003   88         2           NaN              65.0
2004   85         2           NaN              55.0
2001   80         2          50.0               NaN
2002   85         3          52.0               NaN
2003   88         2          50.0               NaN
2004   85         2          53.0               NaN


C:\Users\Windows\Anaconda3\lib\site-packages\pandas\core\frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)
